farmingsoon/BE

- build.gradle
- src/main/java/com/api/farmingsoon/common/exception/ErrorCode.java
- src/main/java/com/api/farmingsoon/common/interceptor/AuthenticationInterceptor.java
- src/main/java/com/api/farmingsoon/common/redis/RedisConfig.java
- src/main/java/com/api/farmingsoon/common/redis/RedisService.java
- src/main/java/com/api/farmingsoon/common/security/config/SecurityConfig.java
- src/main/java/com/api/farmingsoon/common/security/jwt/JwtProvider.java
- src/main/java/com/api/farmingsoon/common/security/jwt/JwtToken.java
- src/main/java/com/api/farmingsoon/common/security/jwt/JwtTokenRes.java
- src/main/java/com/api/farmingsoon/common/security/oauth/CustomOAuth2UserService.java
- src/main/java/com/api/farmingsoon/common/security/oauth/OAuth2Attribute.java
- src/main/java/com/api/farmingsoon/common/security/oauth/OAuthSuccessHandler.java
- src/main/java/com/api/farmingsoon/common/util/JwtUtils.java
- src/main/java/com/api/farmingsoon/domain/member/controller/MemberController.java
- src/main/java/com/api/farmingsoon/domain/member/controller/MemberPageController.java
- src/main/java/com/api/farmingsoon/domain/member/model/Member.java
- src/main/java/com/api/farmingsoon/domain/member/model/MemberRole.java
- src/main/java/com/api/farmingsoon/domain/member/repository/MemberRepository.java
- src/main/java/com/api/farmingsoon/domain/member/service/MemberService.java
- src/main/resources/templates/login.html
- #7
- `플랫폼 연결 끊을 때 accessToken을 가져오는 방법 생각해봐야함.`
This closed #7
> 회원가입 및 로그인 기능 구현2(Social)

- build.gradle
- src/main/java/com/api/farmingsoon/common/exception/ErrorCode.java
- src/main/java/com/api/farmingsoon/common/exception/custom_exception/S3Exception.java
- src/main/java/com/api/farmingsoon/common/s3/config/S3Config.java
- src/main/java/com/api/farmingsoon/common/s3/service/S3Service.java
- src/main/java/com/api/farmingsoon/common/util/MultipartFileUtils.java
- #11 
- AWS S3Bucket에 이미지 업로드하는 기능 구현
This closed #11
> S3 이미지 업로드 기능 구현

- build.gradle
- src/main/java/com/api/farmingsoon/common/auditing/AuditingConfig.java
- src/main/java/com/api/farmingsoon/common/auditing/BaseTimeEntity.java
- src/main/java/com/api/farmingsoon/common/event/UploadImagesRollbackEvent.java
- src/main/java/com/api/farmingsoon/common/exception/ErrorCode.java
- src/main/java/com/api/farmingsoon/common/listener/ImageEventListener.java
- src/main/java/com/api/farmingsoon/common/querydsl/querydslConfig.java
- src/main/java/com/api/farmingsoon/common/s3/service/S3Service.java
- src/main/java/com/api/farmingsoon/common/security/config/SecurityConfig.java
- src/main/java/com/api/farmingsoon/common/util/AuthenticationUtils.java
- src/main/java/com/api/farmingsoon/common/util/TimeUtils.java
- src/main/java/com/api/farmingsoon/domain/image/domain/Image.java
- src/main/java/com/api/farmingsoon/domain/image/repository/ImageRepository.java
- src/main/java/com/api/farmingsoon/domain/image/service/ImageService.java
- src/main/java/com/api/farmingsoon/domain/item/controller/ItemController.java
- src/main/java/com/api/farmingsoon/domain/item/domain/Item.java
- src/main/java/com/api/farmingsoon/domain/item/domain/ItemStatus.java
- src/main/java/com/api/farmingsoon/domain/item/dto/ItemCreateRequest.java
- src/main/java/com/api/farmingsoon/domain/item/dto/ItemListResponse.java
- src/main/java/com/api/farmingsoon/domain/item/dto/ItemResponse.java
- src/main/java/com/api/farmingsoon/domain/item/dto/ItemWithPageResponse.java
- src/main/java/com/api/farmingsoon/domain/item/repository/ItemRepository.java
- src/main/java/com/api/farmingsoon/domain/item/repository/ItemRepositoryCustom.java
- src/main/java/com/api/farmingsoon/domain/item/repository/ItemRepositoryCustomImpl.java
- src/main/java/com/api/farmingsoon/domain/item/service/ItemService.java
- src/main/java/com/api/farmingsoon/domain/member/model/Member.java
- #13 
- 상품 조회 기능에 필요한 동적 쿼리는 `querydsl`로 구현하는게 좋을 것 같다..
`data jpa`로 구현하면 코드가 조금 복잡해지는 부분이 있는 것 같다.
> Item APi 개발

- build.gradle
- src/main/java/com/api/farmingsoon/common/exception/ErrorCode.java
- src/main/java/com/api/farmingsoon/common/websocket/WebSocketConfig.java
- src/main/java/com/api/farmingsoon/domain/chat/controller/ChatApiController.java
- src/main/java/com/api/farmingsoon/domain/chat/controller/ChatController.java
- src/main/java/com/api/farmingsoon/domain/chat/dto/ChatMessageRequest.java
- src/main/java/com/api/farmingsoon/domain/chat/dto/ChatResponse.java
- src/main/java/com/api/farmingsoon/domain/chat/model/Chat.java
- src/main/java/com/api/farmingsoon/domain/chat/repository/ChatRepository.java
- src/main/java/com/api/farmingsoon/domain/chat/service/ChatService.java
- src/main/java/com/api/farmingsoon/domain/chatroom/controller/ChatRoomController.java
- src/main/java/com/api/farmingsoon/domain/chatroom/dto/ChatRoomCreateRequest.java
- src/main/java/com/api/farmingsoon/domain/chatroom/dto/ChatRoomDetailResponse.java
- src/main/java/com/api/farmingsoon/domain/chatroom/dto/ChatRoomResponse.java
- src/main/java/com/api/farmingsoon/domain/chatroom/model/ChatRoom.java
- src/main/java/com/api/farmingsoon/domain/chatroom/repository/ChatRoomRepository.java
- src/main/java/com/api/farmingsoon/domain/chatroom/service/ChatRoomService.java
- src/main/java/com/api/farmingsoon/domain/item/service/ItemService.java
- #20 
- 채팅방, 채팅 Api구현
- Websocket도입 
- 일단 구현은 했는데 테스트를 못해봐서 결과에 따라 리팩토링을 계속 진행해야 할 것 같고 설명이 필요할 것 같은 부분에 주석으로 표기해두었습니다. 혹시 이해 안가시면 제가 피그마 보면서 따로 설명해드리겠습니다
- 보완해야 할 부분이 좀 많아보여서 같이 피드백해보면 좋을거같습니다. 
This closed #20
> 웹소켓을 이용한 채팅 기능 구현

- src/main/java/com/api/farmingsoon/common/event/BidRegisterEvent.java
- src/main/java/com/api/farmingsoon/common/event/ItemSoldOutEvent.java
- src/main/java/com/api/farmingsoon/domain/bid/controller/BidController.java
- src/main/java/com/api/farmingsoon/domain/bid/model/Bid.java
- src/main/java/com/api/farmingsoon/domain/bid/model/BidResult.java
- src/main/java/com/api/farmingsoon/domain/bid/service/BidService.java
- src/main/java/com/api/farmingsoon/domain/chat/controller/ChatApiController.java
- src/main/java/com/api/farmingsoon/domain/chat/repository/ChatRepository.java
- src/main/java/com/api/farmingsoon/domain/chat/service/ChatService.java
- src/main/java/com/api/farmingsoon/domain/chatroom/dto/ChatRoomDetailResponse.java
- src/main/java/com/api/farmingsoon/domain/chatroom/service/ChatRoomService.java
- src/main/java/com/api/farmingsoon/domain/item/controller/ItemController.java
- src/main/java/com/api/farmingsoon/domain/item/domain/Item.java
- src/main/java/com/api/farmingsoon/domain/item/service/ItemService.java
- src/main/java/com/api/farmingsoon/domain/notification/model/Notification.java
- src/main/java/com/api/farmingsoon/domain/notification/service/NotificationService.java
- #27 
- 판매 완료 시 낙찰자와 입찰에 실패한 사용자에게 분기 처리가 필요하고 알림 부분까지 엮여있어서 따로 이슈 파서 추가 작업 진행하겠습니다. 
This closed #27
> 누락된 기능 추가 및 전체적인 리팩토링

- src/main/java/com/api/farmingsoon/domain/bid/service/BidService.java
- src/main/java/com/api/farmingsoon/domain/item/service/ItemService.java
- src/main/java/com/api/farmingsoon/domain/notification/event/BidEndEvent.java
- src/main/java/com/api/farmingsoon/domain/notification/event/BidRegisterEvent.java
- src/main/java/com/api/farmingsoon/domain/notification/event/ItemSoldOutEvent.java
- src/main/java/com/api/farmingsoon/domain/notification/listener/NotificationEventListener.java
- src/main/java/com/api/farmingsoon/domain/notification/service/NotificationService.java
> 알림 저장 및 전송 로직 작성

- .github/workflows/work.yml
X
- 깃헙액션 서버에서의 레디스 테스트를 위한 설치
- java를 두 번 설치하고 있던 부분 제거
> workflow파일 수정

- .gitignore
- src/main/java/com/api/farmingsoon/common/clean/DatabaseCleanup.java
- src/main/resources/application-dev.yml
- src/main/resources/application-test.yml
- src/main/resources/application.yml
- src/test/java/com/api/farmingsoon/domain/member/controller/MemberControllerTest.java
> 테스트 환경 분리 + secret.yml도입

- .github/workflows/work.yml
- src/main/resources/application-dev.yml
- src/main/resources/application-test.yml
- src/main/resources/application.yml
> 테스트 환경 분리 추가 수정

- src/main/java/com/api/farmingsoon/common/clean/DatabaseCleanup.java
- src/main/java/com/api/farmingsoon/domain/like/controller/LikeableItemController.java
- src/main/java/com/api/farmingsoon/domain/like/model/LikeableItem.java
- src/main/java/com/api/farmingsoon/domain/like/repository/LikeableItemRepository.java
- src/main/java/com/api/farmingsoon/domain/like/service/LikeableItemService.java
- #50 
- like는 DB의 예약어이기 때문에 문제가 발생 -> likeableItem으로 변경
> 예약어에 따른 관심 상품 엔티티명 변경

- src/main/java/com/api/farmingsoon/domain/bid/dto/BidRequest.java
- src/main/java/com/api/farmingsoon/domain/item/controller/ItemController.java
- src/main/java/com/api/farmingsoon/domain/item/domain/Item.java
- src/main/java/com/api/farmingsoon/domain/item/dto/ItemDetailResponse.java
- src/main/java/com/api/farmingsoon/domain/item/dto/ItemListResponse.java
- src/main/java/com/api/farmingsoon/domain/item/repository/ItemRepositoryCustom.java
- src/main/java/com/api/farmingsoon/domain/item/repository/ItemRepositoryCustomImpl.java
- src/main/java/com/api/farmingsoon/domain/item/service/ItemService.java
- src/test/java/com/api/farmingsoon/domain/item/controller/ItemControllerTest.java
- #52 
- 최신순 - recent
- 인기순 - hot
- 고가순 - highest 
- 저가순 - lowest
this closed #52
> 상품 테스트 작성 및 리팩토링

- src/main/java/com/api/farmingsoon/domain/item/controller/ItemController.java
- src/main/java/com/api/farmingsoon/domain/item/domain/Item.java
- src/main/java/com/api/farmingsoon/domain/item/dto/ItemDetailResponse.java
- src/main/java/com/api/farmingsoon/domain/item/dto/ItemListResponse.java
- src/main/java/com/api/farmingsoon/domain/item/repository/ItemRepository.java
- src/main/java/com/api/farmingsoon/domain/item/repository/ItemRepositoryCustomImpl.java
- src/main/java/com/api/farmingsoon/domain/item/service/ItemService.java
- src/test/java/com/api/farmingsoon/domain/item/controller/ItemControllerTest.java
- #58 
- api 스펙 변경(판매자 ID, 상품 이미지, 조회수 추가)
- 상품 soft delete적용
- 삭제, 수정 권한체킹 버그 수정(osiv, 논리오류)
- 상품 목록 조회 버그 수정(아우터 조인으로 변경)
- 상품 삭제 테스트 작성
this closed #58
> 상품 도메인 테스트 자동화 및 리팩토링3

- src/main/java/com/api/farmingsoon/common/alert/discord/DiscordService.java
- src/main/java/com/api/farmingsoon/common/alert/discord/DiscordUtil.java
- src/main/java/com/api/farmingsoon/common/auditing/BaseTimeEntity.java
- src/main/java/com/api/farmingsoon/common/exception/GlobalExceptionHandler.java
- src/main/java/com/api/farmingsoon/domain/item/domain/Item.java
> 서버 에러 모니터링 도입

- src/main/java/com/api/farmingsoon/domain/item/dto/ItemDetailResponse.java
- src/main/java/com/api/farmingsoon/domain/item/dto/ItemListResponse.java
- src/main/java/com/api/farmingsoon/domain/item/service/ItemService.java
- src/main/java/com/api/farmingsoon/domain/like/controller/LikeableItemController.java
- src/main/java/com/api/farmingsoon/domain/like/repository/LikeableItemRepository.java
- src/main/java/com/api/farmingsoon/domain/like/service/LikeableItemService.java
- src/test/java/com/api/farmingsoon/domain/like/controller/LikeableItemIntegrationTest.java
- src/test/java/com/api/farmingsoon/util/Transaction.java
- src/test/java/com/api/farmingsoon/util/TransactionFunction.java
- #66 
https://cl8d.tistory.com/120
https://hudi.blog/jpa-lazy-loading-issue-during-e2e-testing/
This closed #66
> 관심 상품 테스트 자동화 및 리팩토링

- src/main/java/com/api/farmingsoon/domain/bid/dto/BidListResponse.java
- src/main/java/com/api/farmingsoon/domain/bid/service/BidService.java
- src/main/java/com/api/farmingsoon/domain/chat/controller/ChatApiController.java
- src/main/java/com/api/farmingsoon/domain/chat/dto/ChatListResponse.java
- src/main/java/com/api/farmingsoon/domain/chat/service/ChatService.java
- src/main/java/com/api/farmingsoon/domain/chatroom/service/ChatRoomService.java
- src/main/java/com/api/farmingsoon/domain/image/service/ImageService.java
- src/main/java/com/api/farmingsoon/domain/notification/controller/NotificationController.java
- src/main/java/com/api/farmingsoon/domain/notification/dto/NotificationListResponse.java
- src/main/java/com/api/farmingsoon/domain/notification/repository/NotificationRepository.java
- src/main/java/com/api/farmingsoon/domain/notification/service/NotificationService.java
> 알림, 채팅 페이징 처리

- src/main/java/com/api/farmingsoon/domain/bid/dto/BidListResponse.java
> 입찰 api스펙 변경

- src/main/java/com/api/farmingsoon/domain/notification/controller/NotificationController.java
- src/main/java/com/api/farmingsoon/domain/notification/model/Notification.java
- src/main/java/com/api/farmingsoon/domain/notification/service/NotificationService.java
- src/test/java/com/api/farmingsoon/domain/notification/NotificationIntegrationTest.java
> 알림 테스트 자동화 및 리팩토링

- src/main/java/com/api/farmingsoon/common/redis/RedisConfig.java
- src/main/java/com/api/farmingsoon/domain/item/domain/Item.java
- src/main/java/com/api/farmingsoon/domain/item/dto/ItemCreateRequest.java
- src/main/java/com/api/farmingsoon/domain/item/listener/BidEndListener.java
- src/main/java/com/api/farmingsoon/domain/item/service/ItemRedisService.java
- src/main/java/com/api/farmingsoon/domain/item/service/ItemService.java
- src/test/java/com/api/farmingsoon/domain/chatting/ChattingIntegrationTest.java
- src/test/java/com/api/farmingsoon/domain/item/ItemIntegrationTest.java
- src/test/java/com/api/farmingsoon/domain/like/LikeableItemIntegrationTest.java
- src/test/java/com/api/farmingsoon/domain/notification/NotificationIntegrationTest.java
- #84 
https://wildeveloperetrain.tistory.com/299
> 입찰 마감 기능 구현

- src/main/java/com/api/farmingsoon/domain/chat/repository/ChatRepository.java
- src/main/java/com/api/farmingsoon/domain/chat/service/ChatService.java
- src/test/java/com/api/farmingsoon/domain/chatting/ChattingIntegrationTest.java
> 채팅 순서대로 저장 및 조회

- src/main/java/com/api/farmingsoon/common/interceptor/AuthenticationInterceptor.java
- src/main/java/com/api/farmingsoon/common/interceptor/StompInterceptor.java
- src/main/java/com/api/farmingsoon/common/security/jwt/JwtProvider.java
- src/main/java/com/api/farmingsoon/common/security/jwt/JwtToken.java
- src/main/java/com/api/farmingsoon/common/security/oauth/OAuthSuccessHandler.java
- src/main/java/com/api/farmingsoon/common/util/CookieUtils.java
- src/main/java/com/api/farmingsoon/common/util/JwtUtils.java
- src/main/java/com/api/farmingsoon/domain/chatroom/controller/ChatRoomController.java
- src/main/java/com/api/farmingsoon/domain/member/controller/MemberController.java
- src/main/java/com/api/farmingsoon/domain/member/dto/LoginResponse.java
- src/main/java/com/api/farmingsoon/domain/member/service/MemberService.java
> 쿠키를 통해 토큰 전달하는 방식으로 변경

- src/main/java/com/api/farmingsoon/common/sse/SseService.java
- src/main/java/com/api/farmingsoon/domain/chat/controller/ChatController.java
- src/main/java/com/api/farmingsoon/domain/chat/event/ChatSaveEvent.java
- src/main/java/com/api/farmingsoon/domain/chat/listener/ChatEventListener.java
- src/main/java/com/api/farmingsoon/domain/chat/service/ChatService.java
- src/main/java/com/api/farmingsoon/domain/chatroom/dto/ChatRoomDetailResponse.java
- src/main/java/com/api/farmingsoon/domain/chatroom/dto/ChatRoomResponse.java
- src/main/java/com/api/farmingsoon/domain/chatroom/model/ChatRoom.java
- src/main/java/com/api/farmingsoon/domain/image/event/UploadImagesRollbackEvent.java
- src/main/java/com/api/farmingsoon/domain/image/listener/ImageEventListener.java
- src/main/java/com/api/farmingsoon/domain/image/service/ImageService.java
- src/main/java/com/api/farmingsoon/domain/item/service/ItemService.java
- src/main/java/com/api/farmingsoon/domain/member/controller/MemberController.java
- src/main/java/com/api/farmingsoon/domain/notification/listener/NotificationSaveEventListener.java
> SSE최적화 밑작업

- build.gradle
- src/main/java/com/api/farmingsoon/common/exception/GlobalExceptionHandler.java
- src/main/java/com/api/farmingsoon/common/init/InitData.java
- src/main/java/com/api/farmingsoon/common/redis/RedisConfig.java
- src/main/java/com/api/farmingsoon/common/redis/event/RedisResponseDelayEvent.java
- src/main/java/com/api/farmingsoon/common/redis/event/RedisRestartEvent.java
- src/main/java/com/api/farmingsoon/common/redis/listener/KeyExpirationListener.java
- src/main/java/com/api/farmingsoon/common/redis/listener/RedisEventListener.java
- src/main/java/com/api/farmingsoon/common/scheduler/CustomSchedulerRunner.java
- src/main/java/com/api/farmingsoon/common/scheduler/SchedulerRunner.java
- src/main/java/com/api/farmingsoon/common/util/TimeUtils.java
- src/main/java/com/api/farmingsoon/common/util/Transaction.java
- src/main/java/com/api/farmingsoon/common/util/TransactionFunction.java
- src/main/java/com/api/farmingsoon/domain/item/event/BidEndKeyExpiredEvent.java
- src/main/java/com/api/farmingsoon/domain/item/event/BidEndSchedulerRunEvent.java
- src/main/java/com/api/farmingsoon/domain/item/event/ItemSaveEvent.java
- src/main/java/com/api/farmingsoon/domain/item/listener/ItemEventListener.java
- src/main/java/com/api/farmingsoon/domain/item/repository/ItemRepositoryCustom.java
- src/main/java/com/api/farmingsoon/domain/item/repository/ItemRepositoryCustomImpl.java
- src/main/java/com/api/farmingsoon/domain/item/service/ItemService.java
- src/main/resources/application-dev.yml
- src/main/resources/application.yml
- #114 
-> 입찰 마감 및 Redis 재 시작 감지
- 하위 메서드부터 트랜잭션 시작 시 적용안되는 문제 발생 -> 외부 트랜잭션 도입하여 해결 
This closed #114
> Redis장애 감지 및 대응에 대한 시나리오 작성

- src/main/java/com/api/farmingsoon/common/auditing/BaseTimeEntity.java
- src/main/java/com/api/farmingsoon/domain/item/domain/Item.java
- src/main/java/com/api/farmingsoon/domain/item/repository/ItemRepository.java
> softDelete에 따른 조회조건 추가

- src/main/java/com/api/farmingsoon/common/interceptor/StompInterceptor.java
- src/main/java/com/api/farmingsoon/domain/chat/controller/ChatController.java
- src/main/java/com/api/farmingsoon/domain/chat/dto/ChatResponse.java
- src/main/java/com/api/farmingsoon/domain/chat/dto/ReadMessageRequest.java
- src/main/java/com/api/farmingsoon/domain/chat/model/Chat.java
- src/main/java/com/api/farmingsoon/domain/chat/repository/ChatRepository.java
- src/main/java/com/api/farmingsoon/domain/chat/repository/ChatRepositoryCustom.java
- src/main/java/com/api/farmingsoon/domain/chat/repository/ChatRepositoryCustomImpl.java
- src/main/java/com/api/farmingsoon/domain/chat/service/ChatService.java
- src/main/java/com/api/farmingsoon/domain/chatroom/dto/ChatRoomResponse.java
- src/main/java/com/api/farmingsoon/domain/chatroom/event/ChatRoomConnectEvent.java
- src/main/java/com/api/farmingsoon/domain/chatroom/listener/ChatRoomEventListener.java
- src/test/java/com/api/farmingsoon/domain/chatting/ChattingIntegrationTest.java
> 채팅 읽지 않은 메시지 처리

- src/main/java/com/api/farmingsoon/domain/member/service/MemberService.java
- #128 
- 이미지 정합성 보장을 위한 외부 트랜잭션 도입
> 회원가입 프로필 이미지 정합성 보장

- src/main/java/com/api/farmingsoon/domain/chat/listener/ChatEventListener.java
- src/main/java/com/api/farmingsoon/domain/chat/repository/ChatRepository.java
- src/main/java/com/api/farmingsoon/domain/chat/service/ChatService.java
- src/test/java/com/api/farmingsoon/domain/chatting/ChattingIntegrationTest.java
> 채팅 발신 시에도 목록 최신화 알림 발행 

- src/main/java/com/api/farmingsoon/common/interceptor/AuthenticationInterceptor.java
- src/main/java/com/api/farmingsoon/common/interceptor/WebSocketHandshakeInterceptor.java
> 웹소켓 연결 전 인증 처리

- src/main/java/com/api/farmingsoon/common/security/oauth/OAuthSuccessHandler.java
> 소셜 로그인 리팩토링
